package com.revature.models;

public class Order {

    private int order_id;
    private String name;
    private double price;

    /*Employees in Java will contain entire Role objects instead of just an int foreign key
      an int FK is less useful to us than an entire Role object
      If we have an entire Role object, we have access to all the Role's DATA as well. (not just a number) */
    private Customer customer;

    //Another role_id_fk field to be used with inserts (lets us skip the Role object when inserting)
    private int customer_id_fk;

    //boilerplate code-------------

    //no-args constructor
    public Order() {
    }

    //all-args constructor
    public Order(int order_id, String name, double price, int customer_id_fk) {
        this.order_id = order_id;
        this.name = name;
        this.price = price;
        this.customer_id_fk = customer_id_fk;
    }

    public Order(int order_id, String name, double price) {
        this.order_id = order_id;
        this.name = name;
        this.price = price;
    }

    //Constructor to be used with inserts (no id, and role_id_fk instead of Role)
    //-No id because it's serial and will be autogenerated by the DB
    //-role_id_fk so we don't have to supply an entire Role in the HTTP Request
    public Order(String name, double price, int customer_id_fk) {
        this.name = name;
        this.price = price;
        this.customer_id_fk = customer_id_fk;
    }

    //getters and setters
    public int getOrder_id() {
        return order_id;
    }

    public void setOrder_id(int order_id) {
        this.order_id = order_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public int getCustomer_id_fk() {
        return customer_id_fk;
    }

    public void setCustomer_id_fk(int customer_id_fk) {
        this.customer_id_fk = customer_id_fk;
    }

    //toString
    @Override
    public String toString() {
        return "Order{" +
                "order_id=" + order_id +
                ", name='" + name + '\'' +
                ", price='" + price + '\'' +
                ", customer_fk_id=" + customer_id_fk +
                '}';
    }
}
